/*
* Time-lapse project
* Author: Sergey Firsov
*/

#include <ESP8266WiFi.h>
#include "webPageContent.h"

void WebPageContent::send(ESP8266WebServer* server) {

    const int sizeOfText = 14000;

    char* temp = new char[sizeOfText];
    snprintf(temp, sizeOfText,
         "<!DOCTYPE html>\n"
         "<html lang=\"en\">\n"
         "<head>\n"
         "    <meta charset=\"utf-8\">\n"
         "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
         "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
         "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"\n"
         "          integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\n"
         "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css\"\n"
         "          integrity=\"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r\" crossorigin=\"anonymous\">\n"
         "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n"
         "    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"\n"
         "            integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\"\n"
         "            crossorigin=\"anonymous\"></script>\n"
         "    <style>\n"
         "        .row {\n"
         "            padding-top: 15px;\n"
         "            padding-bottom: 15px;\n"
         "        }\n"
         "    </style>\n"
         "</head>\n"
         "<body>\n"
         "<div class=\"container\">\n"
         "    <div class=\"page-header\">\n"
         "        <h1>Timelapse project</h1>\n"
         "    </div>\n"
         "    <div class=\"row\">\n"
         "        <div class=\"col-xs-12\">\n"
         "            <p>Select your camera</p>\n"
         "            <select id=\"select-camera\" class=\"btn btn-default form-control\">\n"
         "                <option value=\"0\">Sony</option>\n"
         "                <option value=\"1\">Nikon</option>\n"
         "                <option value=\"2\">Canon</option>\n"
         "                <option value=\"3\">Pentax</option>\n"
         "                <option value=\"4\">Olympus</option>\n"
         "                <option value=\"5\">Minolta</option>\n"
         "            </select>\n"
         "        </div>\n"
         "    </div>\n"
         "    <div class=\"row\">\n"
         "        <div class=\"col-xs-12\">\n"
         "            <div class=\"radio\">\n"
         "                <label><input type=\"radio\" id=\"normal-mode\" name=\"shutter-mode\" value=\"normal-mode\" checked>Normal mode</label>\n"
         "            </div>\n"
         "            <div class=\"radio\">\n"
         "                <label><input type=\"radio\" id=\"bulb-mode\" name=\"shutter-mode\" value=\"bulb-mode\">Bulb mode</label>\n"
         "            </div>\n"
         "        </div>\n"
         "    </div>\n"
         "    <div class=\"row\">\n"
         "        <div class=\"col-xs-12\">\n"
         "            <div class=\"input-group\">\n"
         "                <span class=\"input-group-addon\" id=\"pause-between-shutter-addon\">Shooting rate in millis</span>\n"
         "                <input type=\"number\" min=\"5000\" value=\"6000\" step=\"100\" class=\"form-control\" id=\"pause-between-shutter\" aria-describedby=\"pause-between-shutter-addon\">\n"
         "            </div>\n"
         "        </div>\n"
         "    </div>\n"
         "    <div class=\"row\" id=\"shutter-delay-row\" hidden=\"true\">\n"
         "        <div class=\"col-xs-12\">\n"
         "            <div class=\"input-group\">\n"
         "                <span class=\"input-group-addon\" id=\"shutter-open-time-addon\">Shutter open time</span>\n"
         "                <input type=\"number\" min=\"1000\" value=\"2000\" step=\"100\" class=\"form-control\" id=\"shutter-open-time\" aria-describedby=\"shutter-open-time-addon\">\n"
         "            </div>\n"
         "        </div>\n"
         "    </div>\n"
         "    <div id=\"iterations\">\n"
         "\n"
         "    </div>\n"
         "    <div class=\"row\">\n"
         "        <div class=\"col-xs-6 text-center\">\n"
         "            <button class=\"btn btn-success form-control\" id=\"add-stay\">Add stay</button>\n"
         "        </div>\n"
         "        <div class=\"col-xs-6 text-center\">\n"
         "            <button class=\"btn btn-success form-control\" id=\"add-move\">Add move</button>\n"
         "        </div>\n"
         "    </div>\n"
         "    <div class=\"row\">\n"
         "        <div class=\"col-xs-12 text-center\">\n"
         "            <button class=\"btn btn-warning form-control\" id=\"go\">Go!</button>\n"
         "        </div>\n"
         "    </div>\n"
         "    <div class=\"row\" id=\"statistics-row\" hidden=\"true\">\n"
         "        <div class=\"col-xs-12 text-center\">\n"
         "            <p id=\"statistics\"></p>\n"
         "        </div>\n"
         "    </div>\n"
         "</div>\n"
         "\n"
         "<div class=\"row jumbotron\" id=\"iteration-move-block\" hidden=\"true\">\n"
         "    <div class=\"col-xs-12\">\n"
         "        <div class=\"row\">\n"
         "            <div class=\"col-xs-12\">\n"
         "                <div class=\"radio\">\n"
         "                    <label><input type=\"radio\" id=\"clockwise\" name=\"rotate-direction\" value=\"clockwise\" checked>Rotate clockwise</label>\n"
         "                </div>\n"
         "                <div class=\"radio\">\n"
         "                    <label><input type=\"radio\" id=\"counter-clockwise\" name=\"rotate-direction\" value=\"counter-clockwise\">Rotate counter clockwise</label>\n"
         "                </div>\n"
         "            </div>\n"
         "        </div>\n"
         "        <div class=\"row\">\n"
         "            <div class=\"col-xs-12\">\n"
         "                <div class=\"input-group\">\n"
         "                    <span class=\"input-group-addon\" id=\"rotation-degree-addon\">Enter rotation angle</span>\n"
         "                    <input type=\"number\" min=\"0\" max=\"10000\" step=\"1\" class=\"form-control\" id=\"rotation-degree\" aria-describedby=\"rotation-degree-addon\">\n"
         "                </div>\n"
         "            </div>\n"
         "        </div>\n"
         "        <div class=\"row\">\n"
         "            <div class=\"col-xs-12\">\n"
         "                <div class=\"input-group\">\n"
         "                    <span class=\"input-group-addon\" id=\"steps-per-shot-addon\">Steps per 1 photo</span>\n"
         "                    <input type=\"number\" min=\"0\" max=\"10000\" step=\"1\" class=\"form-control\" id=\"steps-per-shot\"\n"
         "                           aria-describedby=\"steps-per-shot-addon\">\n"
         "                </div>\n"
         "            </div>\n"
         "        </div>\n"
         "    </div>\n"
         "</div>\n"
         "\n"
         "<div class=\"row jumbotron\" id=\"iteration-stay-block\" hidden=\"true\">\n"
         "    <div class=\"col-xs-12\">\n"
         "        <div class=\"row\">\n"
         "            <div class=\"col-xs-12\">\n"
         "                <div class=\"input-group\">\n"
         "                    <span class=\"input-group-addon\" id=\"stay-for-addon\">Stay for</span>\n"
         "                    <input type=\"number\" min=\"0\" max=\"10000\" step=\"1\" class=\"form-control\" id=\"stay-for\"\n"
         "                           aria-describedby=\"stay-for-addon\">\n"
         "                </div>\n"
         "            </div>\n"
         "        </div>\n"
         "        <div class=\"row\">\n"
         "            <div class=\"col-xs-12\">\n"
         "                <div class=\"radio\">\n"
         "                    <label><input type=\"radio\" name=\"time-scale-mode\" value=\"60000\" checked>Minutes</label>\n"
         "                </div>\n"
         "                <div class=\"radio\">\n"
         "                    <label><input type=\"radio\" name=\"time-scale-mode\" value=\"1000\">Seconds</label>\n"
         "                </div>\n"
         "            </div>\n"
         "        </div>\n"
         "    </div>\n"
         "</div>\n"
         "\n"
         "<script>\n"
         "    var iterationNumber = 0;\n"
         "\n"
         "    var createNextMoveBlock = function() {\n"
         "        var nextIterationBlock = $(\"#iteration-move-block\").clone();\n"
         "\n"
         "        nextIterationBlock.prepend(\"<h2>\" + (iterationNumber + 1) + \"</h2>\");\n"
         "\n"
         "        nextIterationBlock.attr(\"id\", \"iteration-move-block\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#clockwise\").attr(\"id\", \"clockwise\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#clockwise\" + iterationNumber).attr(\"name\", \"rotate-direction\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#counter-clockwise\").attr(\"id\", \"counter-clockwise\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#counter-clockwise\" + iterationNumber).attr(\"name\", \"rotate-direction\" + iterationNumber);\n"
         "\n"
         "        nextIterationBlock.find(\"#rotation-degree-addon\").attr(\"id\", \"rotation-degree-addon\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#rotation-degree\").attr(\"id\", \"rotation-degree\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#rotation-degree\" + iterationNumber).attr(\"aria-describedby\", \"rotation-degree-addon\" + iterationNumber);\n"
         "\n"
         "        nextIterationBlock.find(\"#steps-per-shot-addon\").attr(\"id\", \"steps-per-shot-addon\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#steps-per-shot\").attr(\"id\", \"steps-per-shot\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#steps-per-shot\" + iterationNumber).attr(\"aria-describedby\", \"steps-per-shot-addon\" + iterationNumber);\n"
         "\n"
         "        nextIterationBlock.attr(\"hidden\", false);\n"
         "\n"
         "        iterationNumber++;\n"
         "\n"
         "        return nextIterationBlock;\n"
         "    };\n"
         "\n"
         "    var createNextStayBlock = function () {\n"
         "        var nextIterationBlock = $(\"#iteration-stay-block\").clone();\n"
         "\n"
         "        nextIterationBlock.prepend(\"<h2>\" + (iterationNumber + 1) + \"</h2>\");\n"
         "\n"
         "        nextIterationBlock.attr(\"id\", \"iteration-stay-block\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"#stay-for\").attr(\"id\", \"stay-for\" + iterationNumber);\n"
         "        nextIterationBlock.find(\"input[name=time-scale-mode]\").attr(\"name\", \"time-scale-mode\" + iterationNumber);\n"
         "\n"
         "        nextIterationBlock.attr(\"hidden\", false);\n"
         "\n"
         "        iterationNumber++;\n"
         "\n"
         "        return nextIterationBlock;\n"
         "    };\n"
         "\n"
         "    var validation = function () {\n"
         "        var result = true;\n"
         "\n"
         "        var pauseBetweenShutterMin = 5000;\n"
         "        var shutterMode = $(\"input[name=shutter-mode]:checked\").val();\n"
         "        if(shutterMode === \"bulb-mode\") {\n"
         "            pauseBetweenShutterMin = 10000;\n"
         "        }\n"
         "\n"
         "        var pauseBetweenShutterVal = $(\"#pause-between-shutter\").val();\n"
         "        if (parseInt(pauseBetweenShutterVal) < pauseBetweenShutterMin) {\n"
         "            $(\"#pause-between-shutter\").val(pauseBetweenShutterMin);\n"
         "            result = false;\n"
         "            alert(\"Pause between shutter was set incorrectly.\");\n"
         "        }\n"
         "\n"
         "        if (shutterMode === \"bulb-mode\") {\n"
         "            var shutterOpenTime = $(\"#shutter-open-time\").val();\n"
         "            if (parseInt(shutterOpenTime) < 1000 || (parseInt(shutterOpenTime) > parseInt(pauseBetweenShutterVal) - 5000)) {\n"
         "                $(\"#shutter-open-time\").val(2000);\n"
         "                result = false;\n"
         "                alert(\"Shutter open time was set incorrectly.\");\n"
         "            }\n"
         "        }\n"
         "\n"
         "        return result;\n"
         "    };\n"
         "\n"
         "    $(\"#normal-mode\").click(function () {\n"
         "        $(\"#shutter-delay-row\").attr(\"hidden\", true);\n"
         "        $(\"#pause-between-shutter\").val(6000);\n"
         "        $(\"#shutter-open-time\").val(2000);\n"
         "    });\n"
         "\n"
         "    $(\"#bulb-mode\").click(function () {\n"
         "        $(\"#shutter-delay-row\").attr(\"hidden\", false);\n"
         "        $(\"#pause-between-shutter\").val(15000);\n"
         "        $(\"#shutter-open-time\").val(5000);\n"
         "    });\n"
         "\n"
         "    $(\"#add-move\").click(function () {\n"
         "        var newIterationBlock = createNextMoveBlock();\n"
         "        $(\"#iterations\").append(newIterationBlock);\n"
         "    });\n"
         "\n"
         "    $(\"#add-stay\").click(function () {\n"
         "        var newIterationBlock = createNextStayBlock();\n"
         "        $(\"#iterations\").append(newIterationBlock);\n"
         "    });\n"
         "\n"
         "    $(\"#go\").click(function () {\n"
         "\n"
         "        if (validation() === false) {\n"
         "            return;\n"
         "        }\n"
         "\n"
         "        var requestParams = {};\n"
         "\n"
         "        var selectedCamera = $(\"#select-camera option:selected\").text();\n"
         "        requestParams[\"selectedCamera\"] = selectedCamera;\n"
         "\n"
         "        var shutterMode = $(\"input[name=shutter-mode]:checked\").val();\n"
         "        requestParams[\"shutterMode\"] = shutterMode;\n"
         "\n"
         "        var pauseBetweenShutter = $(\"#pause-between-shutter\").val();\n"
         "        requestParams[\"pauseBetweenShutter\"] = pauseBetweenShutter;\n"
         "\n"
         "        var shutterOpenTime = $(\"#shutter-open-time\").val();\n"
         "        requestParams[\"shutterOpenTime\"] = shutterOpenTime;\n"
         "\n"
         "        var iterations = $(\"#iterations\").children();\n"
         "\n"
         "        var requiredTimeStatistics = 0;\n"
         "        var i = 0;\n"
         "        iterations.each(function () {\n"
         "            var iter = $(this);\n"
         "            var iterationId = iter.attr(\"id\");\n"
         "\n"
         "            if (iterationId === (\"iteration-move-block\" + i)) {\n"
         "                var degreeValue = iter.find(\"#rotation-degree\" + i).val();\n"
         "                if (degreeValue < 0) {\n"
         "                    degreeValue = 0;\n"
         "                }\n"
         "                else if (degreeValue > 10000) {\n"
         "                    degreeValue = 10000;\n"
         "                }\n"
         "                var direction = iter.find(\"#clockwise\" + i).prop(\"checked\") ? 1 : -1;\n"
         "                iter.find(\"#rotation-degree\" + i).val(degreeValue);\n"
         "\n"
         "                var oneStep = iter.find(\"#steps-per-shot\" + i).val();\n"
         "\n"
         "                requestParams[\"degree\" + i] = degreeValue;\n"
         "                requestParams[\"direction\" + i] = direction;\n"
         "                requestParams[\"step\" + i] = oneStep;\n"
         "                requestParams[\"stay\" + i] = 0;\n"
         "                requestParams[\"timeScale\" + i] = 1;\n"
         "\n"
         "                requiredTimeStatistics += (parseInt(degreeValue) * 2048 / 360) / parseInt(oneStep) * parseInt(pauseBetweenShutter);\n"
         "            }\n"
         "            else if (iterationId === (\"iteration-stay-block\" + i)){\n"
         "                var timeScale = iter.find(\"input[name=time-scale-mode\" + i + \"]:checked\").val();\n"
         "                requestParams[\"timeScale\" + i] = timeScale;\n"
         "\n"
         "                var stayFor = iter.find(\"#stay-for\" + i).val();\n"
         "                requestParams[\"stay\" + i] = parseInt(stayFor);\n"
         "\n"
         "                requiredTimeStatistics += parseInt(stayFor) * parseInt(timeScale);\n"
         "            }\n"
         "\n"
         "            iter = iterations.next();\n"
         "            i++;\n"
         "        });\n"
         "        requestParams[\"iterationsNumber\"] = iterations.length;\n"
         "\n"
         "        $.post(\"/go\", requestParams);\n"
         "\n"
         "        $(\"#statistics-row\").attr(\"hidden\", false);\n"
         "        var hours   = parseFloat(requiredTimeStatistics) / 60000 / 60;\n"
         "        var minutes = (hours - Math.floor(hours)) * 60;\n"
         "        $(\"#statistics\").text(\"It will take approximately \" + Math.floor(hours) + \" hours and \" + Math.round(minutes) + \" minutes to finish the sequence. Relax and have a glass of wine or beer.\");\n"
         "    });\n"
         "\n"
         "</script>\n"
         "</body>\n"
         "</html>");

    server->send(200, "text/html", temp);

    delete [] temp;
}

void WebPageContent::pageNotFound(ESP8266WebServer* server) {
    const int sizeOfText = 3000;

    char* temp = new char[sizeOfText];
    snprintf(temp, sizeOfText,
         "<!DOCTYPE html>\n"
         "<html lang=\"en\">\n"
         "<head>\n"
         "    <meta charset=\"utf-8\">\n"
         "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
         "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
         "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"\n"
         "          integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\n"
         "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css\"\n"
         "          integrity=\"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r\" crossorigin=\"anonymous\">\n"
         "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\n"
         "    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"\n"
         "            integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\"\n"
         "            crossorigin=\"anonymous\"></script>\n"
         "    <style>\n"
         "        .row {\n"
         "            padding-top: 15px;\n"
         "            padding-bottom: 15px;\n"
         "        }\n"
         "    </style>\n"
         "</head>\n"
         "<body>\n"
         "<div class=\"container\">\n"
         "    <div class=\"page-header\">\n"
         "        <h1>Timelapse project</h1>\n"
         "    </div>\n"
         "    <h2 class=\"text-center\">Page not found</h2>\n"
         "</div>\n"
         "</body>");

    server->send(404, "text/html", temp);

    delete [] temp;
}